#!/usr/bin/env python3
"""Generate the Rose palette and shape stylesheets.

The Rose appearance is pref-driven CSS, not JavaScript. Gecko's chrome CSS
supports `@media -moz-pref("name", value)` for boolean, integer and string
prefs, so a palette can be a string pref and a corner radius an integer one,
and the whole interface restyles the instant the pref changes — no window
enumeration, no flash of the previous theme on startup, nothing to keep in
sync with a second implementation.

The cost is that each discrete value needs its own block, which is why this is
generated: 25 palettes and six shape axes is several thousand lines of
mechanical CSS that would otherwise be written and maintained by hand.

Run from the repository root:

    python3 fennec/browser/themes/rose/generate.py

then, because the output is mechanical rather than formatted:

    ./mach lint --fix fennec/browser/themes/rose/

and commit both. The stylesheets are deliberately checked in: the build must
not need a Python step for files that change twice a year.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
LICENCE = """/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
"""

GENERATED = """
/* Generated by fennec/browser/themes/rose/generate.py — do not edit.
 * Change rose-themes.json, or the generator, and run it again. */

/* stylelint-disable stylelint-plugin-mozilla/use-design-tokens --
 * These files define the Rose tokens; there is nothing above them to use. */
"""

PREF = "rose.appearance"


# ── Colour helpers ────────────────────────────────────────────────


def channels(colour: str) -> tuple[int, int, int]:
    text = colour.lstrip("#")
    if len(text) == 3:
        text = "".join(character * 2 for character in text)
    return tuple(int(text[index : index + 2], 16) for index in (0, 2, 4))


def luma(colour: str) -> float:
    red, green, blue = channels(colour)
    return (red * 299 + green * 587 + blue * 114) / 1000


def mix(first: str, second: str, amount: float) -> str:
    one, two = channels(first), channels(second)
    return "#" + "".join(
        f"{max(0, min(255, round(a + (b - a) * amount))):02x}" for a, b in zip(one, two)
    )


def rgb_parts(colour: str) -> str:
    """`r g b`, for building `rgb(… / alpha)` in the stylesheet."""
    return " ".join(str(part) for part in channels(colour))


def readable_on(background: str, dark: str, light: str) -> str:
    return dark if luma(background) > 140 else light


# ── Palettes ──────────────────────────────────────────────────────


def palette_block(key: str, palette: dict) -> str:
    """One palette, as the variables the rest of the theme reads.

    Everything downstream reads these names and nothing else, so a palette is
    data and the stylesheet never mentions a literal colour.
    """
    background = palette["background"]
    surface = palette["surface"]
    panel = palette["panel"]
    elevated = palette["elevated"]
    accent = palette["accent"]
    accent_muted = palette["accent_muted"]
    text = palette["text"]
    dim = palette["text_dim"]
    border = palette["border"]
    light = luma(background) > 140

    # A hover that shows on a near-black palette and on a near-white one. A
    # fixed white overlay is invisible on the light palettes.
    hover = mix(panel, text, 0.10 if not light else 0.07)
    field = mix(surface, text, 0.06 if not light else 0.035)

    return f"""
@media -moz-pref("{PREF}.palette", "{key}") {{
  :root {{
    --rose-scheme: {"light" if light else "dark"};

    --rose-backdrop: {background};
    --rose-surface: {surface};
    --rose-panel: {panel};
    --rose-elevated: {elevated};
    --rose-field: {field};
    --rose-hover: {hover};

    --rose-border: {border};
    --rose-border-strong: {mix(border, text, 0.25)};

    --rose-text: {text};
    --rose-text-dim: {dim};
    --rose-text-faint: {mix(dim, background, 0.35)};
    --rose-text-inverse: {readable_on(accent, background, text)};

    --rose-accent: {accent};
    --rose-accent-hover: {mix(accent, text, 0.15)};
    --rose-accent-muted: {accent_muted};
    --rose-accent-rgb: {rgb_parts(accent)};

    --rose-success: {palette["success"]};
    --rose-warning: {palette["warning"]};
    --rose-danger: {palette["error"]};

    --rose-backdrop-rgb: {rgb_parts(background)};
    --rose-panel-rgb: {rgb_parts(panel)};
    --rose-elevated-rgb: {rgb_parts(elevated)};
  }}
}}
"""


def palettes_css(palettes: dict) -> str:
    header = f"""{LICENCE}{GENERATED}
/* Every palette, one block each, chosen by the `{PREF}.palette` string pref.
 * The first block is the default and is unconditional, so an unknown or unset
 * pref still produces a complete theme rather than an unstyled window. */
"""
    default_key = "rose-dark"
    default = palettes[default_key]
    body = palette_block(default_key, default).replace(
        f'@media -moz-pref("{PREF}.palette", "{default_key}") {{\n', "", 1
    )
    # Undo the extra indentation left by removing the wrapper.
    body = "\n".join(
        line[2:] if line.startswith("  ") else line
        for line in body.rstrip().rstrip("}").rstrip().splitlines()
    )

    blocks = [header, body, ""]
    blocks += [palette_block(key, palette) for key, palette in palettes.items()]
    return "\n".join(blocks)


# ── Shape ─────────────────────────────────────────────────────────

#: Every numeric axis, as (pref, variable, unit, values). Discrete steps
#: rather than a free number, because each value costs a CSS block — and
#: because a corner radius of 7 versus 8 is not a choice anybody needs.
AXES: tuple[tuple[str, str, str, tuple[int, ...]], ...] = (
    ("radius", "--rose-radius", "px", (0, 2, 4, 6, 8, 12, 16, 22)),
    ("padding", "--rose-padding", "px", (0, 2, 4, 6, 8, 12, 16)),
    ("border-width", "--rose-border-width", "px", (0, 1, 2)),
    ("font-size", "--rose-font-size", "px", (11, 12, 13, 14, 15, 16, 17, 18, 20)),
    ("tab-height", "--rose-tab-height", "px", (28, 32, 36, 40, 44)),
    ("glass-blur", "--rose-glass-blur", "px", (0, 6, 12, 20, 32)),
    ("glass-opacity", "--rose-glass-opacity", "%", (60, 70, 80, 90, 100)),
    (
        "gradient-angle",
        "--rose-gradient-angle",
        "deg",
        (0, 45, 90, 135, 160, 180, 225, 270),
    ),
    ("gradient-strength", "--rose-gradient-strength", "%", (0, 4, 8, 12, 20, 30)),
)

#: Defaults, used for the unconditional block. A pref that is unset, or set to
#: a value this stylesheet has no block for, still gets a complete theme.
DEFAULTS = {
    "radius": 8,
    "padding": 6,
    "border-width": 1,
    "font-size": 14,
    "tab-height": 36,
    "glass-blur": 12,
    "glass-opacity": 80,
    "gradient-angle": 160,
    "gradient-strength": 8,
}

#: Font stacks offered in the appearance settings. Only families that are
#: actually on a normal Linux desktop: a picker listing fonts that silently
#: fall back is worse than a short one, because the setting looks broken.
FONTS: tuple[tuple[str, str], ...] = (
    ("system", 'system-ui, -apple-system, "Liberation Sans", sans-serif'),
    ("adwaita", '"Adwaita Sans", system-ui, sans-serif'),
    ("inter", '"Inter", system-ui, sans-serif'),
    ("rubik", '"Rubik", system-ui, sans-serif'),
    ("space-grotesk", '"Space Grotesk", system-ui, sans-serif'),
    ("readex", '"Readex Pro", system-ui, sans-serif'),
    ("liberation", '"Liberation Sans", Arial, sans-serif'),
    ("serif", '"FreeSerif", Georgia, serif'),
    ("hack", '"Hack", ui-monospace, monospace'),
    ("jetbrains", '"JetBrainsMono NFM", ui-monospace, monospace'),
)


def shape_css() -> str:
    lines = [
        LICENCE,
        GENERATED,
        """
/* The shape of the interface: how round, how dense, how big the text, and
 * whether surfaces are frosted or flat. Each axis is an integer pref with a
 * block per step; the unconditional block at the top is the default, so an
 * unset pref is a complete theme rather than a missing variable. */

:root {""",
    ]

    for name, variable, unit, _values in AXES:
        lines.append(f"  {variable}: {DEFAULTS[name]}{unit};")

    lines.append(f"  --rose-font: {FONTS[0][1]};")
    lines.append("""
  /* Built from the axes above so the rest of the stylesheet asks for one
     thing rather than reassembling them at every use. */
  --rose-glass-tint: rgb(var(--rose-panel-rgb) / calc(var(--rose-glass-opacity) / 100));
  --rose-fill-backdrop: var(--rose-backdrop);
  --rose-fill-panel: var(--rose-panel);
  --rose-fill-elevated: var(--rose-elevated);
  --rose-fill-accent: var(--rose-accent);
}
""")

    for name, variable, unit, values in AXES:
        lines.append(f"/* {name} */")
        for value in values:
            lines.append(
                f'@media -moz-pref("{PREF}.{name}", {value}) {{\n'
                f"  :root {{ {variable}: {value}{unit}; }}\n"
                f"}}"
            )
        lines.append("")

    lines.append("/* interface font */")
    for key, stack in FONTS:
        lines.append(
            f'@media -moz-pref("{PREF}.font", "{key}") {{\n'
            f"  :root {{ --rose-font: {stack}; }}\n"
            f"}}"
        )
    lines.append("")

    lines.append("""/* Gradients. Off by default: a gradient is a strong look and the palettes
 * are designed flat. When on, every surface gains a fill built from its own
 * colour, so one switch restyles the window rather than nine. */
@media -moz-pref("rose.appearance.gradient", true) {
  :root {
    --rose-fill-backdrop: linear-gradient(
      var(--rose-gradient-angle),
      color-mix(in srgb, var(--rose-backdrop), white var(--rose-gradient-strength)),
      var(--rose-backdrop)
    );
    --rose-fill-panel: linear-gradient(
      var(--rose-gradient-angle),
      color-mix(in srgb, var(--rose-panel), white var(--rose-gradient-strength)),
      var(--rose-panel)
    );
    --rose-fill-elevated: linear-gradient(
      var(--rose-gradient-angle),
      color-mix(in srgb, var(--rose-elevated), white var(--rose-gradient-strength)),
      var(--rose-elevated)
    );
    --rose-fill-accent: linear-gradient(
      var(--rose-gradient-angle),
      color-mix(in srgb, var(--rose-accent), white var(--rose-gradient-strength)),
      var(--rose-accent)
    );
  }
}
""")

    return "\n".join(lines)


def scoped(css: str) -> str:
    """Wrap a generated sheet so it only reaches the browser's own documents.

    These are registered as a user sheet, which applies to every document
    including web pages. Custom properties paint nothing by themselves, but a
    page inheriting two hundred --rose-* variables is untidy and confusing in
    devtools.
    """
    head, _, body = css.partition("*/")
    indented = "\n".join(
        ("  " + line) if line.strip() else line for line in body.strip().splitlines()
    )
    return f'{head}*/\n\n@-moz-document url-prefix("chrome://"), url-prefix("about:") {{\n{indented}\n}}\n'


def main() -> int:
    palettes = json.loads((HERE / "rose-themes.json").read_text(encoding="utf-8"))

    (HERE / "rose-palettes.css").write_text(
        scoped(palettes_css(palettes)), encoding="utf-8"
    )
    (HERE / "rose-shape.css").write_text(scoped(shape_css()), encoding="utf-8")

    keys = write_themes(palettes)

    (HERE / "generated-jar.mn.inc").write_text(jar_lines(keys), encoding="utf-8")

    pane = (
        HERE.parent.parent.parent.parent
        / "browser"
        / "components"
        / "preferences"
        / "config"
        / "rose-palettes.mjs"
    )
    pane.write_text(palette_module(palettes), encoding="utf-8")
    (HERE / "generated-themes.inc").write_text(config_entries(keys), encoding="utf-8")

    print(f"wrote rose-palettes.css and rose-shape.css ({len(palettes)} palettes)")
    print(
        f"wrote {len(keys)} built-in themes, plus the jar.mn and "
        f"BuiltInThemeConfig fragments to paste"
    )
    return 0


# ── Built-in themes ───────────────────────────────────────────────
#
# The stylesheet cannot reach everything: in-content pages, the tab strip's
# own painting and anything the theme system owns are set by a lightweight
# theme. Every palette therefore also exists as a built-in theme add-on, and
# RoseAppearance switches to the one matching the palette pref.

THEMES_DIR = HERE.parent.parent.parent.parent / "browser" / "themes" / "addons"


def theme_id(key: str) -> str:
    """The add-on directory and id for a palette key.

    Palette keys are bare names — "tokyo-night", "light" — and theme ids are
    prefixed, because an add-on id is global and because `addons/light` is
    Firefox's own Light theme. Writing a palette called "light" there would
    overwrite it, and deleting by key would remove it.
    """
    return key if key.startswith("rose-") else f"rose-{key}"


def theme_manifest(key: str, palette: dict) -> dict:
    background = palette["background"]
    surface = palette["surface"]
    panel = palette["panel"]
    elevated = palette["elevated"]
    accent = palette["accent"]
    accent_muted = palette["accent_muted"]
    text = palette["text"]
    dim = palette["text_dim"]
    border = palette["border"]
    scheme = "light" if luma(background) > 140 else "dark"

    return {
        "manifest_version": 2,
        "browser_specific_settings": {"gecko": {"id": f"{theme_id(key)}@fennec"}},
        "name": palette["name"],
        "description": f"The {palette['name']} palette, shared with the other Rose applications.",
        "author": "Rose Open Source Endeavours",
        "version": "1.0.0",
        "icons": {"32": "icon.svg"},
        "theme": {
            "colors": {
                "frame": background,
                "frame_inactive": background,
                "tab_background_text": dim,
                "tab_selected": elevated,
                "tab_text": text,
                "tab_line": accent,
                "tab_loading": accent,
                "toolbar": surface,
                "toolbar_text": text,
                "toolbar_field": panel,
                "toolbar_field_text": text,
                "toolbar_field_border": border,
                "toolbar_field_focus": elevated,
                "toolbar_field_text_focus": text,
                "toolbar_field_border_focus": accent,
                "toolbar_top_separator": border,
                "toolbar_bottom_separator": border,
                "toolbar_vertical_separator": border,
                "ntp_background": background,
                "ntp_text": text,
                "popup": panel,
                "popup_text": text,
                "popup_border": border,
                "popup_highlight": accent_muted,
                "popup_highlight_text": text,
                "sidebar": surface,
                "sidebar_text": text,
                "sidebar_border": border,
                "sidebar_highlight": accent_muted,
                "sidebar_highlight_text": text,
                "button_background_hover": panel,
                "button_background_active": elevated,
                "icons": dim,
                "icons_attention": accent,
                "bookmark_text": text,
                "error_text": palette["error"],
            },
            "properties": {"color_scheme": scheme, "content_color_scheme": scheme},
        },
    }


SVG_LICENCE = "<!-- This Source Code Form is subject to the terms of the Mozilla Public\n   - License, v. 2.0. If a copy of the MPL was not distributed with this\n   - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->\n"


def theme_icon(palette: dict) -> str:
    return (
        SVG_LICENCE
        + '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32">\n'
        f'  <rect width="32" height="32" rx="7" fill="{palette["background"]}"/>\n'
        f'  <rect x="4" y="6" width="24" height="7" rx="3" fill="{palette["surface"]}"/>\n'
        f'  <rect x="4" y="16" width="24" height="10" rx="3" fill="{palette["panel"]}"/>\n'
        f'  <circle cx="10" cy="21" r="3" fill="{palette["accent"]}"/>\n'
        "</svg>\n"
    )


def theme_preview(palette: dict) -> str:
    return (
        SVG_LICENCE
        + '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 680 92" width="680" height="92">\n'
        f'  <rect width="680" height="92" fill="{palette["background"]}"/>\n'
        f'  <rect x="0" y="0" width="680" height="34" fill="{palette["surface"]}"/>\n'
        f'  <rect x="12" y="8" width="150" height="20" rx="6" fill="{palette["panel"]}"/>\n'
        f'  <rect x="170" y="8" width="120" height="20" rx="6" fill="{palette["background"]}"/>\n'
        f'  <rect x="12" y="44" width="656" height="26" rx="8" fill="{palette["panel"]}"/>\n'
        f'  <circle cx="640" cy="18" r="7" fill="{palette["accent"]}"/>\n'
        "</svg>\n"
    )


def write_themes(palettes: dict) -> list[str]:
    written = []
    for key, palette in palettes.items():
        folder = THEMES_DIR / theme_id(key)
        folder.mkdir(parents=True, exist_ok=True)
        (folder / "manifest.json").write_text(
            json.dumps(theme_manifest(key, palette), indent=2) + "\n", encoding="utf-8"
        )
        (folder / "icon.svg").write_text(theme_icon(palette), encoding="utf-8")
        (folder / "preview.svg").write_text(theme_preview(palette), encoding="utf-8")
        written.append(theme_id(key))
    return written


def jar_lines(keys: list[str]) -> str:
    lines = ["  # ── Rose palettes ──"]
    for key in keys:
        for name in ("manifest.json", "icon.svg", "preview.svg"):
            lines.append(
                f"  content/builtin-themes/{key}/{name}".ljust(62) + f"({key}/{name})"
            )
    return "\n".join(lines) + "\n"


def palette_module(palettes: dict) -> str:
    """The palette list the settings pane offers.

    Generated so the pane, the stylesheet and the built-in themes cannot drift:
    a palette added to rose-themes.json appears in all three.
    """
    rows = "\n".join(
        f'  ["{key}", "{palette["name"]}"],' for key, palette in palettes.items()
    )
    return (
        "/* This Source Code Form is subject to the terms of the Mozilla Public\n"
        " * License, v. 2.0. If a copy of the MPL was not distributed with this\n"
        " * file, You can obtain one at http://mozilla.org/MPL/2.0/. */\n\n"
        "/* Generated by fennec/browser/themes/rose/generate.py — do not edit. */\n\n"
        "export const ROSE_PALETTES = [\n" + rows + "\n];\n"
    )


def config_entries(keys: list[str]) -> str:
    blocks = []
    for key in keys:
        blocks.append(
            f'  [\n    "{key}@fennec",\n    {{\n'
            f'      version: "1.0.0",\n'
            f'      path: "resource://builtin-themes/{key}/",\n'
            f"    }},\n  ],"
        )
    return "\n".join(blocks) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
