.TH FENNEC 1 "June 2026" "Fennec" "Fennec Manual"
.SH NAME
fennec \- a privacy conscious web browser
.SH SYNOPSIS
.B fennec
[\fIOPTIONS\fR] [\fIURL\fR]
.SH DESCRIPTION
Fennec is a customizable, privacy conscious web browser based on Firefox.
.SH OPTIONS
.TP
.B \-\-new\-window \fIURL\fR
Open \fIURL\fR in a new window.
.TP
.B \-\-private\-window \fIURL\fR
Open \fIURL\fR in a new private window.
.TP
.B \-\-ProfileManager
Start with the profile manager.
.PP
For the full list of options, run \fBfennec \-\-help\fR.
.SH FILES
.TP
.I /usr/lib/fennec
The Fennec installation directory.
.SH BUGS
Report issues at https://github.com/BrowserWorks/Fennec/issues.
.SH SEE ALSO
.I https://www.waterfox.net/
